#!/bin/bash

# Get the directory where the script is located
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
PYTHON_SCRIPT_PATH="$SCRIPT_DIR/check_appointments.py"
LOG_FILE_PATH="$SCRIPT_DIR/dmv_check.log"

# Ensure the Python script is executable
chmod +x "$PYTHON_SCRIPT_PATH"

echo "DMV Appointment Checker Cron Job Setup"
echo "---------------------------------------"
echo "This script will help you set up a cron job to run the Python script."
echo ""
echo "Python script path: $PYTHON_SCRIPT_PATH"
echo "Log file path: $LOG_FILE_PATH"
echo ""
echo "To run the script, for example, every day at 8 AM, you would add the following line to your crontab:"
echo ""
echo "0 8 * * * /usr/bin/python3 $PYTHON_SCRIPT_PATH >> $LOG_FILE_PATH 2>&1"
echo ""
echo "Explanation of the cron schedule (0 8 * * *):"
echo "  - 0: Minute (0-59) -> 0th minute (at the start of the hour)"
echo "  - 8: Hour (0-23) -> 8 AM"
echo "  - *: Day of the month (1-31) -> Every day"
echo "  - *: Month (1-12) -> Every month"
echo "  - *: Day of the week (0-7, where 0 and 7 are Sunday) -> Every day of the week"
echo ""
echo "To edit your crontab, run the command:"
echo "  crontab -e"
echo ""
echo "Then, paste the cron job line (e.g., the one above for 8 AM daily) into the file, save, and exit."
echo "Make sure that '/usr/bin/python3' is the correct path to your Python 3 interpreter. You can find it by running 'which python3'."
echo "If it's different, update the cron job line accordingly."
echo ""
echo "You can choose a different schedule. For example, to run every 4 hours:"
echo "0 */4 * * * /usr/bin/python3 $PYTHON_SCRIPT_PATH >> $LOG_FILE_PATH 2>&1"
echo ""
echo "To run twice a day, at 8 AM and 6 PM:"
echo "0 8,18 * * * /usr/bin/python3 $PYTHON_SCRIPT_PATH >> $LOG_FILE_PATH 2>&1"
echo ""
echo "The output of the script (including any found appointments or errors) will be appended to $LOG_FILE_PATH."
echo "Remember to check this log file periodically."
echo ""
echo "Setup helper finished. Please add the cron job manually using 'crontab -e'."
